transformer:
  embed_size: 384       
  num_heads: 8           
  num_layers: 4          
  max_len: 320          
  dropout: 0.1           
  bias: false            
  embed_type: position  
encoder:
  type: resnet50_v2

decoder:
  type: transformer        
scheduler:
  active: true       
  first_cycle_steps: 1600  
  cycle_mult: 1  
  max_lr: 0.0005       
  min_lr: 0.00003
  warmup_steps: 160
  gamma: 0.99 
dataloader:
  num_workers: 0
  type: normal  
img_size: [64,256]
lr: 0.0001          
label_smoothing: 0.1
max_grad_norm: 0.5
batch_size: 64       
num_epochs: 200
save_per_epochs: 1
print_type: per_epoch
seed: 0
